<a href="https://colab.research.google.com/github/Pranav-Bankar/Data_Science_Lab_SE_A_03/blob/main/Simple_Python_Programs/Expt_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Welcome to Colab!

### Create a 3x3 Matrix and Compute its Determinant

First, we'll take input from the user to create a 3x3 matrix. Then, we'll use NumPy to calculate its determinant.

In [ ]:
import numpy as np

matrix = []
print("Enter the elements of the 3x3 matrix row by row:")
for i in range(3):
    row = []
    for j in range(3):
        while True:
            try:
                element = float(input(f"Enter element at position ({i+1},{j+1}): "))
                row.append(element)
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
    matrix.append(row)

matrix_np = np.array(matrix)
print("\nYour 3x3 matrix is:")
display(matrix_np)

In [1]:
import numpy as np
determinant = np.linalg.det(matrix_np)
print(f"\nThe determinant of the matrix is: {determinant}")

NameError: name 'np' is not defined

### Create a 3x3 Matrix and Compute its Determinant

First, we'll take input from the user to create a 3x3 matrix. Then, we'll use NumPy to calculate its determinant.

In [2]:
import numpy as np

matrix = []
print("Enter the elements of the 3x3 matrix row by row:")
for i in range(3):
    row = []
    for j in range(3):
        while True:
            try:
                element = float(input(f"Enter element at position ({i+1},{j+1}): "))
                row.append(element)
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
    matrix.append(row)

matrix_np = np.array(matrix)
print("\nYour 3x3 matrix is:")
display(matrix_np)

Enter the elements of the 3x3 matrix row by row:
Enter element at position (1,1): 5
Enter element at position (1,2): 6
Enter element at position (1,3): 4
Enter element at position (2,1): 3
Enter element at position (2,2): 54
Enter element at position (2,3): 3
Enter element at position (3,1): 2
Enter element at position (3,2): 2
Enter element at position (3,3): 4

Your 3x3 matrix is:


array([[ 5.,  6.,  4.],
       [ 3., 54.,  3.],
       [ 2.,  2.,  4.]])

In [3]:
import numpy as np
determinant = np.linalg.det(matrix_np)
print(f"\nThe determinant of the matrix is: {determinant}")


The determinant of the matrix is: 605.9999999999999


In [4]:
import numpy as np

inverse_matrix = np.linalg.inv(matrix_np)
print("\nThe inverse of the matrix is:")
display(inverse_matrix)


The inverse of the matrix is:


array([[ 0.34653465, -0.02640264, -0.32673267],
       [-0.00990099,  0.01980198, -0.0049505 ],
       [-0.16831683,  0.00330033,  0.41584158]])

### Solve System of Linear Equations

We will solve the system of linear equations:
1. 2x + 3y = 10
2. 4x + 5y = 20

First, we'll represent these equations in matrix form, Ax = B.

In [5]:
import numpy as np

# Define the coefficient matrix A
A = np.array([[2, 3], [4, 5]])

# Define the result vector B
B = np.array([10, 20])

print("Coefficient Matrix A:")
display(A)
print("\nResult Vector B:")
display(B)

Coefficient Matrix A:


array([[2, 3],
       [4, 5]])


Result Vector B:


array([10, 20])

In [6]:
import numpy as np

# Solve the system of equations using np.linalg.solve()
solution = np.linalg.solve(A, B)

x = solution[0]
y = solution[1]

print(f"The solution to the system of equations is: x = {x}, y = {y}")

The solution to the system of equations is: x = 5.0, y = 0.0


### Create a 3x3 Matrix and Compute its Determinant (Without NumPy)

First, we'll take input from the user to create a 3x3 matrix using standard Python lists. Then, we'll calculate its determinant using a manual formula.

In [7]:
# Function to display a matrix
def display_matrix(matrix):
    for row in matrix:
        print(row)

matrix_no_np = []
print("Enter the elements of the 3x3 matrix row by row:")
for i in range(3):
    row = []
    for j in range(3):
        while True:
            try:
                element = float(input(f"Enter element at position ({i+1},{j+1}): "))
                row.append(element)
                break
            except ValueError:
                print("Invalid input. Please enter a number.")
    matrix_no_np.append(row)

print("\nYour 3x3 matrix is:")
display_matrix(matrix_no_np)

Enter the elements of the 3x3 matrix row by row:
Enter element at position (1,1): 4
Enter element at position (1,2): 6
Enter element at position (1,3): 3
Enter element at position (2,1): 7
Enter element at position (2,2): 9
Enter element at position (2,3): 2
Enter element at position (3,1): 4
Enter element at position (3,2): 3
Enter element at position (3,3): 1

Your 3x3 matrix is:
[4.0, 6.0, 3.0]
[7.0, 9.0, 2.0]
[4.0, 3.0, 1.0]


In [8]:
# Function to calculate the determinant of a 3x3 matrix manually
def calculate_determinant_3x3(matrix):
    if len(matrix) != 3 or any(len(row) != 3 for row in matrix):
        raise ValueError("Matrix must be 3x3")

    # Formula for 3x3 determinant:
    # a(ei - fh) - b(di - fg) + c(dh - eg)
    # Where matrix is [[a, b, c], [d, e, f], [g, h, i]]

    a, b, c = matrix[0]
    d, e, f = matrix[1]
    g, h, i = matrix[2]

    determinant = a * (e * i - f * h) - b * (d * i - f * g) + c * (d * h - e * g)
    return determinant

determinant_no_np = calculate_determinant_3x3(matrix_no_np)
print(f"\nThe determinant of the matrix (without NumPy) is: {determinant_no_np}")


The determinant of the matrix (without NumPy) is: -27.0
